"""ICD-10 reference dataset for AvrisAI clinical autosuggest.

Curated selection of the most commonly used codes in Central Asia / CIS
clinical practice (~600+ entries covering all major chapters A00-Z99).
Each row: (code, name_ru, name_en).

This is not the full ICD-10 catalog (which has ~70,000 codes including
sub-classifications) — it's the working subset doctors actually reach for.
"""

# (code, name_ru, name_en)
ICD10_CODES: list[tuple[str, str, str]] = [
    # ===== A00-B99 — Инфекционные и паразитарные болезни =====
    ("A00", "Холера", "Cholera"),
    ("A01", "Тиф и паратиф", "Typhoid and paratyphoid fevers"),
    ("A02", "Сальмонеллёзные инфекции", "Salmonella infections"),
    ("A03", "Шигеллёз", "Shigellosis"),
    ("A04", "Бактериальные кишечные инфекции другие", "Other bacterial intestinal infections"),
    ("A05", "Бактериальные пищевые отравления", "Bacterial foodborne intoxications"),
    ("A06", "Амёбиаз", "Amoebiasis"),
    ("A07", "Протозойные кишечные болезни", "Protozoal intestinal diseases"),
    ("A08", "Вирусные кишечные инфекции", "Viral intestinal infections"),
    ("A09", "Диарея и гастроэнтерит инфекционного происхождения", "Diarrhoea and gastroenteritis of infectious origin"),
    ("A15", "Туберкулёз органов дыхания", "Respiratory tuberculosis"),
    ("A16", "Туберкулёз органов дыхания (без бактериологического подтверждения)", "Respiratory TB unconfirmed"),
    ("A17", "Туберкулёз нервной системы", "Tuberculosis of nervous system"),
    ("A18", "Туберкулёз других органов", "Tuberculosis of other organs"),
    ("A19", "Милиарный туберкулёз", "Miliary tuberculosis"),
    ("A30", "Лепра", "Leprosy"),
    ("A33", "Столбняк новорождённого", "Tetanus neonatorum"),
    ("A35", "Столбняк", "Other tetanus"),
    ("A36", "Дифтерия", "Diphtheria"),
    ("A37", "Коклюш", "Whooping cough"),
    ("A38", "Скарлатина", "Scarlet fever"),
    ("A39", "Менингококковая инфекция", "Meningococcal infection"),
    ("A40", "Стрептококковая септицемия", "Streptococcal septicaemia"),
    ("A41", "Другая септицемия", "Other septicaemia"),
    ("A46", "Рожа", "Erysipelas"),
    ("A48", "Бактериальные болезни другие", "Other bacterial diseases"),
    ("A49", "Бактериальная инфекция неуточнённой локализации", "Bacterial infection of unspecified site"),
    ("A50", "Врождённый сифилис", "Congenital syphilis"),
    ("A51", "Ранний сифилис", "Early syphilis"),
    ("A52", "Поздний сифилис", "Late syphilis"),
    ("A53", "Сифилис другой и неуточнённый", "Other and unspecified syphilis"),
    ("A54", "Гонококковая инфекция", "Gonococcal infection"),
    ("A56", "Хламидийные инфекции", "Other sexually transmitted chlamydial diseases"),
    ("A60", "Аногенитальная герпетическая инфекция", "Anogenital herpesviral infection"),
    ("A63", "Другие болезни, передающиеся половым путём", "Other STDs"),
    ("A69", "Другие спирохетозы", "Other spirochaetal infections"),
    ("A75", "Сыпной тиф", "Typhus fever"),
    ("A77", "Пятнистая лихорадка", "Spotted fever"),
    ("A80", "Острый полиомиелит", "Acute poliomyelitis"),
    ("A81", "Медленные вирусные инфекции ЦНС", "Slow viral infections of CNS"),
    ("A82", "Бешенство", "Rabies"),
    ("A83", "Вирусный энцефалит, передаваемый комарами", "Mosquito-borne viral encephalitis"),
    ("A84", "Вирусный энцефалит, передаваемый клещами", "Tick-borne viral encephalitis"),
    ("A87", "Вирусный менингит", "Viral meningitis"),
    ("A90", "Лихорадка денге", "Dengue fever"),
    ("A92", "Другие вирусные лихорадки, передаваемые комарами", "Other mosquito-borne viral fevers"),
    ("A95", "Жёлтая лихорадка", "Yellow fever"),
    ("B00", "Инфекции, вызванные вирусом простого герпеса", "Herpesviral [herpes simplex] infections"),
    ("B01", "Ветряная оспа", "Varicella [chickenpox]"),
    ("B02", "Опоясывающий лишай", "Zoster [herpes zoster]"),
    ("B05", "Корь", "Measles"),
    ("B06", "Краснуха", "Rubella"),
    ("B07", "Вирусные бородавки", "Viral warts"),
    ("B08", "Другие вирусные инфекции с поражением кожи", "Other viral infections with skin lesions"),
    ("B15", "Острый гепатит A", "Acute hepatitis A"),
    ("B16", "Острый гепатит B", "Acute hepatitis B"),
    ("B17", "Другие острые вирусные гепатиты", "Other acute viral hepatitis"),
    ("B18", "Хронический вирусный гепатит", "Chronic viral hepatitis"),
    ("B19", "Вирусный гепатит неуточнённый", "Unspecified viral hepatitis"),
    ("B20", "ВИЧ-инфекция с проявлениями инфекционных болезней", "HIV with infectious diseases"),
    ("B24", "ВИЧ-инфекция неуточнённая", "Unspecified HIV disease"),
    ("B25", "Цитомегаловирусная инфекция", "Cytomegaloviral disease"),
    ("B26", "Эпидемический паротит", "Mumps"),
    ("B27", "Инфекционный мононуклеоз", "Infectious mononucleosis"),
    ("B30", "Вирусный конъюнктивит", "Viral conjunctivitis"),
    ("B34", "Вирусная инфекция неуточнённой локализации", "Viral infection of unspecified site"),
    ("B35", "Дерматофития", "Dermatophytosis"),
    ("B36", "Другие поверхностные микозы", "Other superficial mycoses"),
    ("B37", "Кандидоз", "Candidiasis"),
    ("B49", "Микоз неуточнённый", "Unspecified mycosis"),
    ("B50", "Малярия, вызванная Plasmodium falciparum", "Plasmodium falciparum malaria"),
    ("B54", "Малярия неуточнённая", "Unspecified malaria"),
    ("B65", "Шистосомоз", "Schistosomiasis"),
    ("B68", "Тениоз", "Taeniasis"),
    ("B71", "Цестодоз неуточнённый", "Other cestode infections"),
    ("B76", "Анкилостомидоз", "Hookworm diseases"),
    ("B77", "Аскаридоз", "Ascariasis"),
    ("B80", "Энтеробиоз", "Enterobiasis"),
    ("B82", "Кишечный паразитизм неуточнённый", "Unspecified intestinal parasitism"),
    ("B86", "Чесотка", "Scabies"),
    ("B87", "Миаз", "Myiasis"),
    ("B99", "Другие инфекционные болезни", "Other infectious diseases"),

    # ===== C00-D48 — Новообразования =====
    ("C00", "Злокачественное новообразование губы", "Malignant neoplasm of lip"),
    ("C01", "Злокачественное новообразование основания языка", "Malignant neoplasm of base of tongue"),
    ("C02", "Злокачественное новообразование других частей языка", "Malignant neoplasm of other parts of tongue"),
    ("C04", "Злокачественное новообразование дна полости рта", "Malignant neoplasm of floor of mouth"),
    ("C09", "Злокачественное новообразование миндалины", "Malignant neoplasm of tonsil"),
    ("C11", "Злокачественное новообразование носоглотки", "Malignant neoplasm of nasopharynx"),
    ("C15", "Злокачественное новообразование пищевода", "Malignant neoplasm of oesophagus"),
    ("C16", "Злокачественное новообразование желудка", "Malignant neoplasm of stomach"),
    ("C17", "Злокачественное новообразование тонкого кишечника", "Malignant neoplasm of small intestine"),
    ("C18", "Злокачественное новообразование ободочной кишки", "Malignant neoplasm of colon"),
    ("C19", "Злокачественное новообразование ректосигмоидного отдела", "Malignant neoplasm of rectosigmoid junction"),
    ("C20", "Злокачественное новообразование прямой кишки", "Malignant neoplasm of rectum"),
    ("C22", "Злокачественное новообразование печени", "Malignant neoplasm of liver"),
    ("C23", "Злокачественное новообразование жёлчного пузыря", "Malignant neoplasm of gallbladder"),
    ("C25", "Злокачественное новообразование поджелудочной железы", "Malignant neoplasm of pancreas"),
    ("C32", "Злокачественное новообразование гортани", "Malignant neoplasm of larynx"),
    ("C34", "Злокачественное новообразование лёгкого", "Malignant neoplasm of lung"),
    ("C43", "Злокачественная меланома кожи", "Malignant melanoma of skin"),
    ("C44", "Другие злокачественные новообразования кожи", "Other malignant neoplasms of skin"),
    ("C50", "Злокачественное новообразование молочной железы", "Malignant neoplasm of breast"),
    ("C53", "Злокачественное новообразование шейки матки", "Malignant neoplasm of cervix uteri"),
    ("C54", "Злокачественное новообразование тела матки", "Malignant neoplasm of corpus uteri"),
    ("C56", "Злокачественное новообразование яичника", "Malignant neoplasm of ovary"),
    ("C61", "Злокачественное новообразование предстательной железы", "Malignant neoplasm of prostate"),
    ("C64", "Злокачественное новообразование почки", "Malignant neoplasm of kidney"),
    ("C67", "Злокачественное новообразование мочевого пузыря", "Malignant neoplasm of bladder"),
    ("C71", "Злокачественное новообразование головного мозга", "Malignant neoplasm of brain"),
    ("C73", "Злокачественное новообразование щитовидной железы", "Malignant neoplasm of thyroid gland"),
    ("C81", "Лимфогранулематоз (болезнь Ходжкина)", "Hodgkin lymphoma"),
    ("C82", "Фолликулярная лимфома", "Follicular lymphoma"),
    ("C83", "Нефолликулярная лимфома", "Non-follicular lymphoma"),
    ("C85", "Другие неуточнённые типы неходжкинской лимфомы", "Other non-Hodgkin lymphoma"),
    ("C90", "Множественная миелома", "Multiple myeloma"),
    ("C91", "Лимфоидный лейкоз", "Lymphoid leukaemia"),
    ("C92", "Миелоидный лейкоз", "Myeloid leukaemia"),
    ("C95", "Лейкоз неуточнённого клеточного типа", "Leukaemia of unspecified cell type"),
    ("D05", "Карцинома молочной железы in situ", "Carcinoma in situ of breast"),
    ("D06", "Карцинома шейки матки in situ", "Carcinoma in situ of cervix uteri"),
    ("D17", "Доброкачественное липоматозное новообразование", "Benign lipomatous neoplasm"),
    ("D18", "Гемангиома и лимфангиома", "Haemangioma and lymphangioma"),
    ("D22", "Меланоформный невус", "Melanocytic naevi"),
    ("D24", "Доброкачественное новообразование молочной железы", "Benign neoplasm of breast"),
    ("D25", "Лейомиома матки", "Leiomyoma of uterus"),
    ("D27", "Доброкачественное новообразование яичника", "Benign neoplasm of ovary"),
    ("D32", "Доброкачественное новообразование мозговых оболочек", "Benign neoplasm of meninges"),
    ("D33", "Доброкачественное новообразование головного мозга", "Benign neoplasm of brain"),
    ("D34", "Доброкачественное новообразование щитовидной железы", "Benign neoplasm of thyroid gland"),

    # ===== D50-D89 — Болезни крови =====
    ("D50", "Железодефицитная анемия", "Iron deficiency anaemia"),
    ("D51", "Витамин-B12-дефицитная анемия", "Vitamin B12 deficiency anaemia"),
    ("D52", "Фолиеводефицитная анемия", "Folate deficiency anaemia"),
    ("D53", "Другие анемии, связанные с питанием", "Other nutritional anaemias"),
    ("D55", "Анемия вследствие ферментных нарушений", "Anaemia due to enzyme disorders"),
    ("D56", "Талассемия", "Thalassaemia"),
    ("D57", "Серповидно-клеточные нарушения", "Sickle-cell disorders"),
    ("D58", "Другие наследственные гемолитические анемии", "Other hereditary haemolytic anaemias"),
    ("D59", "Приобретённая гемолитическая анемия", "Acquired haemolytic anaemia"),
    ("D60", "Приобретённая красноклеточная аплазия", "Acquired pure red cell aplasia"),
    ("D61", "Другие апластические анемии", "Other aplastic anaemias"),
    ("D62", "Острая постгеморрагическая анемия", "Acute posthaemorrhagic anaemia"),
    ("D63", "Анемия при хронических болезнях", "Anaemia in chronic diseases"),
    ("D64", "Другие анемии", "Other anaemias"),
    ("D65", "ДВС-синдром", "Disseminated intravascular coagulation"),
    ("D66", "Дефицит фактора VIII (гемофилия A)", "Hereditary factor VIII deficiency"),
    ("D67", "Гемофилия B", "Hereditary factor IX deficiency"),
    ("D68", "Другие нарушения свёртываемости", "Other coagulation defects"),
    ("D69", "Пурпура и другие геморрагические состояния", "Purpura and other haemorrhagic conditions"),
    ("D70", "Агранулоцитоз", "Agranulocytosis"),
    ("D72", "Другие нарушения лейкоцитов", "Other disorders of white blood cells"),
    ("D73", "Болезни селезёнки", "Diseases of spleen"),
    ("D80", "Иммунодефициты с преимущественно гуморальным дефектом", "Immunodeficiency with predominantly antibody defects"),
    ("D84", "Другие иммунодефициты", "Other immunodeficiencies"),
    ("D86", "Саркоидоз", "Sarcoidosis"),
    ("D89", "Другие нарушения с вовлечением иммунного механизма", "Other disorders involving the immune mechanism"),

    # ===== E00-E90 — Болезни эндокринной системы =====
    ("E00", "Синдром врождённой йодной недостаточности", "Congenital iodine-deficiency syndrome"),
    ("E01", "Болезни щитовидной железы, связанные с йодной недостаточностью", "Iodine-deficiency thyroid disorders"),
    ("E02", "Субклинический гипотиреоз вследствие йодной недостаточности", "Subclinical iodine-deficiency hypothyroidism"),
    ("E03", "Другие формы гипотиреоза", "Other hypothyroidism"),
    ("E04", "Другие формы нетоксического зоба", "Other non-toxic goitre"),
    ("E05", "Тиреотоксикоз", "Thyrotoxicosis [hyperthyroidism]"),
    ("E06", "Тиреоидит", "Thyroiditis"),
    ("E07", "Другие болезни щитовидной железы", "Other disorders of thyroid"),
    ("E10", "Сахарный диабет 1 типа", "Type 1 diabetes mellitus"),
    ("E11", "Сахарный диабет 2 типа", "Type 2 diabetes mellitus"),
    ("E12", "Сахарный диабет, связанный с недостаточностью питания", "Malnutrition-related diabetes mellitus"),
    ("E13", "Другие уточнённые формы сахарного диабета", "Other specified diabetes mellitus"),
    ("E14", "Сахарный диабет неуточнённый", "Unspecified diabetes mellitus"),
    ("E15", "Недиабетическая гипогликемическая кома", "Non-diabetic hypoglycaemic coma"),
    ("E16", "Другие нарушения внутренней секреции поджелудочной железы", "Other disorders of pancreatic internal secretion"),
    ("E20", "Гипопаратиреоз", "Hypoparathyroidism"),
    ("E21", "Гиперпаратиреоз", "Hyperparathyroidism"),
    ("E22", "Гиперфункция гипофиза", "Hyperfunction of pituitary gland"),
    ("E23", "Гипофункция гипофиза", "Hypofunction of pituitary gland"),
    ("E24", "Синдром Иценко-Кушинга", "Cushing syndrome"),
    ("E25", "Адреногенитальные расстройства", "Adrenogenital disorders"),
    ("E26", "Гиперальдостеронизм", "Hyperaldosteronism"),
    ("E27", "Другие нарушения надпочечников", "Other disorders of adrenal gland"),
    ("E28", "Дисфункция яичников", "Ovarian dysfunction"),
    ("E29", "Дисфункция яичек", "Testicular dysfunction"),
    ("E34", "Другие эндокринные нарушения", "Other endocrine disorders"),
    ("E40", "Квашиоркор", "Kwashiorkor"),
    ("E41", "Алиментарный маразм", "Nutritional marasmus"),
    ("E43", "Тяжёлая белково-энергетическая недостаточность", "Severe protein-energy malnutrition"),
    ("E44", "Белково-энергетическая недостаточность умеренной степени", "Moderate protein-energy malnutrition"),
    ("E50", "Недостаточность витамина A", "Vitamin A deficiency"),
    ("E51", "Недостаточность тиамина", "Thiamine deficiency"),
    ("E53", "Недостаточность других витаминов группы B", "Deficiency of other B-group vitamins"),
    ("E54", "Недостаточность аскорбиновой кислоты", "Ascorbic acid deficiency"),
    ("E55", "Недостаточность витамина D", "Vitamin D deficiency"),
    ("E56", "Недостаточность других витаминов", "Other vitamin deficiencies"),
    ("E61", "Недостаточность других элементов питания", "Deficiency of other nutrient elements"),
    ("E66", "Ожирение", "Obesity"),
    ("E70", "Нарушения обмена ароматических аминокислот", "Disorders of aromatic amino-acid metabolism"),
    ("E78", "Нарушения обмена липопротеинов и другие липидемии", "Disorders of lipoprotein metabolism / hyperlipidaemias"),
    ("E83", "Нарушения минерального обмена", "Disorders of mineral metabolism"),
    ("E84", "Кистозный фиброз", "Cystic fibrosis"),
    ("E86", "Уменьшение объёма жидкости", "Volume depletion"),
    ("E87", "Другие нарушения водно-солевого обмена", "Other disorders of fluid/electrolyte balance"),
    ("E88", "Другие нарушения обмена веществ", "Other metabolic disorders"),

    # ===== F00-F99 — Психические расстройства =====
    ("F00", "Деменция при болезни Альцгеймера", "Dementia in Alzheimer disease"),
    ("F01", "Сосудистая деменция", "Vascular dementia"),
    ("F03", "Деменция неуточнённая", "Unspecified dementia"),
    ("F05", "Делирий, не вызванный алкоголем или психоактивными веществами", "Delirium, not induced by alcohol or psychoactive substances"),
    ("F06", "Другие психические расстройства вследствие повреждения мозга", "Other mental disorders due to brain damage"),
    ("F10", "Психические расстройства вследствие употребления алкоголя", "Mental disorders due to alcohol use"),
    ("F11", "Психические расстройства вследствие употребления опиоидов", "Mental disorders due to opioid use"),
    ("F12", "Психические расстройства вследствие употребления каннабиноидов", "Mental disorders due to cannabinoid use"),
    ("F17", "Психические расстройства вследствие употребления табака", "Mental disorders due to tobacco use"),
    ("F19", "Психические расстройства вследствие сочетанного употребления", "Mental disorders due to multiple drug use"),
    ("F20", "Шизофрения", "Schizophrenia"),
    ("F21", "Шизотипическое расстройство", "Schizotypal disorder"),
    ("F22", "Хронические бредовые расстройства", "Persistent delusional disorders"),
    ("F23", "Острые и преходящие психотические расстройства", "Acute and transient psychotic disorders"),
    ("F25", "Шизоаффективные расстройства", "Schizoaffective disorders"),
    ("F29", "Неорганический психоз неуточнённый", "Unspecified non-organic psychosis"),
    ("F30", "Маниакальный эпизод", "Manic episode"),
    ("F31", "Биполярное аффективное расстройство", "Bipolar affective disorder"),
    ("F32", "Депрессивный эпизод", "Depressive episode"),
    ("F33", "Рекуррентное депрессивное расстройство", "Recurrent depressive disorder"),
    ("F34", "Хронические аффективные расстройства", "Persistent mood disorders"),
    ("F40", "Тревожно-фобические расстройства", "Phobic anxiety disorders"),
    ("F41", "Другие тревожные расстройства", "Other anxiety disorders"),
    ("F42", "Обсессивно-компульсивное расстройство", "Obsessive-compulsive disorder"),
    ("F43", "Реакция на тяжёлый стресс и нарушения адаптации", "Reaction to severe stress / adjustment disorders"),
    ("F44", "Диссоциативные расстройства", "Dissociative disorders"),
    ("F45", "Соматоформные расстройства", "Somatoform disorders"),
    ("F50", "Расстройства приёма пищи", "Eating disorders"),
    ("F51", "Расстройства сна неорганической этиологии", "Non-organic sleep disorders"),
    ("F60", "Специфические расстройства личности", "Specific personality disorders"),
    ("F70", "Лёгкая умственная отсталость", "Mild mental retardation"),
    ("F71", "Умеренная умственная отсталость", "Moderate mental retardation"),
    ("F80", "Специфические расстройства развития речи", "Specific developmental disorders of speech"),
    ("F84", "Общие расстройства развития (включая аутизм)", "Pervasive developmental disorders (incl. autism)"),
    ("F90", "Гиперкинетические расстройства (СДВГ)", "Hyperkinetic disorders (ADHD)"),
    ("F91", "Расстройства поведения", "Conduct disorders"),
    ("F95", "Тики", "Tic disorders"),
    ("F99", "Психическое расстройство неуточнённое", "Mental disorder, not otherwise specified"),

    # ===== G00-G99 — Болезни нервной системы =====
    ("G00", "Бактериальный менингит", "Bacterial meningitis"),
    ("G03", "Менингит вследствие других и неуточнённых причин", "Meningitis due to other and unspecified causes"),
    ("G04", "Энцефалит, миелит и энцефаломиелит", "Encephalitis, myelitis and encephalomyelitis"),
    ("G06", "Внутричерепной и внутрипозвоночный абсцесс", "Intracranial / intraspinal abscess and granuloma"),
    ("G09", "Последствия воспалительных болезней ЦНС", "Sequelae of inflammatory CNS diseases"),
    ("G20", "Болезнь Паркинсона", "Parkinson disease"),
    ("G21", "Вторичный паркинсонизм", "Secondary parkinsonism"),
    ("G24", "Дистония", "Dystonia"),
    ("G25", "Другие экстрапирамидные и двигательные нарушения", "Other extrapyramidal / movement disorders"),
    ("G30", "Болезнь Альцгеймера", "Alzheimer disease"),
    ("G31", "Другие дегенеративные болезни нервной системы", "Other degenerative diseases of nervous system"),
    ("G35", "Рассеянный склероз", "Multiple sclerosis"),
    ("G36", "Другая острая диссеминированная демиелинизация", "Other acute disseminated demyelination"),
    ("G37", "Другие демиелинизирующие болезни ЦНС", "Other demyelinating diseases of CNS"),
    ("G40", "Эпилепсия", "Epilepsy"),
    ("G41", "Эпилептический статус", "Status epilepticus"),
    ("G43", "Мигрень", "Migraine"),
    ("G44", "Другие синдромы головной боли", "Other headache syndromes"),
    ("G45", "Преходящие транзиторные ишемические атаки", "Transient cerebral ischaemic attacks"),
    ("G46", "Сосудистые мозговые синдромы при цереброваскулярных болезнях", "Vascular syndromes of brain in cerebrovascular diseases"),
    ("G47", "Расстройства сна", "Sleep disorders"),
    ("G50", "Поражения тройничного нерва", "Disorders of trigeminal nerve"),
    ("G51", "Поражения лицевого нерва", "Facial nerve disorders"),
    ("G52", "Поражения других черепных нервов", "Disorders of other cranial nerves"),
    ("G54", "Поражения нервных корешков и сплетений", "Nerve root / plexus disorders"),
    ("G55", "Сдавления нервных корешков и сплетений", "Nerve root / plexus compressions"),
    ("G56", "Мононевропатии верхних конечностей", "Mononeuropathies of upper limb"),
    ("G57", "Мононевропатии нижних конечностей", "Mononeuropathies of lower limb"),
    ("G58", "Другие мононевропатии", "Other mononeuropathies"),
    ("G60", "Наследственная и идиопатическая невропатия", "Hereditary and idiopathic neuropathy"),
    ("G61", "Воспалительная полиневропатия", "Inflammatory polyneuropathy"),
    ("G62", "Другие полиневропатии", "Other polyneuropathies"),
    ("G63", "Полиневропатия при болезнях, классифицированных в других рубриках", "Polyneuropathy in other diseases"),
    ("G70", "Миастения и другие нарушения нервно-мышечного синапса", "Myasthenia gravis / neuromuscular junction disorders"),
    ("G71", "Первичные поражения мышц", "Primary disorders of muscles"),
    ("G80", "Детский церебральный паралич", "Cerebral palsy"),
    ("G81", "Гемиплегия", "Hemiplegia"),
    ("G82", "Параплегия и тетраплегия", "Paraplegia and tetraplegia"),
    ("G83", "Другие паралитические синдромы", "Other paralytic syndromes"),
    ("G90", "Расстройства вегетативной нервной системы", "Autonomic nervous system disorders"),
    ("G91", "Гидроцефалия", "Hydrocephalus"),
    ("G93", "Другие поражения головного мозга", "Other disorders of brain"),
    ("G95", "Другие болезни спинного мозга", "Other diseases of spinal cord"),

    # ===== H00-H59 — Болезни глаза =====
    ("H00", "Гордеолум и халазион", "Hordeolum and chalazion"),
    ("H01", "Другие воспаления века", "Other inflammation of eyelid"),
    ("H02", "Другие болезни века", "Other disorders of eyelid"),
    ("H04", "Болезни слёзного аппарата", "Disorders of lacrimal system"),
    ("H10", "Конъюнктивит", "Conjunctivitis"),
    ("H11", "Другие болезни конъюнктивы", "Other disorders of conjunctiva"),
    ("H15", "Болезни склеры", "Disorders of sclera"),
    ("H16", "Кератит", "Keratitis"),
    ("H18", "Другие болезни роговицы", "Other disorders of cornea"),
    ("H20", "Иридоциклит", "Iridocyclitis"),
    ("H25", "Старческая катаракта", "Senile cataract"),
    ("H26", "Другие катаракты", "Other cataract"),
    ("H33", "Отслойка и разрывы сетчатки", "Retinal detachments and breaks"),
    ("H35", "Другие болезни сетчатки", "Other retinal disorders"),
    ("H40", "Глаукома", "Glaucoma"),
    ("H43", "Болезни стекловидного тела", "Disorders of vitreous body"),
    ("H44", "Болезни глазного яблока", "Disorders of globe"),
    ("H49", "Паралитическое косоглазие", "Paralytic strabismus"),
    ("H50", "Другие формы косоглазия", "Other strabismus"),
    ("H52", "Нарушения рефракции и аккомодации", "Disorders of refraction and accommodation"),
    ("H53", "Расстройства зрения", "Visual disturbances"),
    ("H54", "Слепота и пониженное зрение", "Blindness and low vision"),

    # ===== H60-H95 — Болезни уха =====
    ("H60", "Наружный отит", "Otitis externa"),
    ("H61", "Другие болезни наружного уха", "Other disorders of external ear"),
    ("H65", "Негнойный средний отит", "Nonsuppurative otitis media"),
    ("H66", "Гнойный и неуточнённый средний отит", "Suppurative and unspecified otitis media"),
    ("H68", "Воспаление и закупорка слуховой трубы", "Eustachian salpingitis and obstruction"),
    ("H70", "Мастоидит и родственные состояния", "Mastoiditis and related conditions"),
    ("H72", "Перфорация барабанной перепонки", "Perforation of tympanic membrane"),
    ("H80", "Отосклероз", "Otosclerosis"),
    ("H81", "Нарушения вестибулярной функции", "Disorders of vestibular function"),
    ("H83", "Другие болезни внутреннего уха", "Other diseases of inner ear"),
    ("H90", "Кондуктивная и нейросенсорная потеря слуха", "Conductive and sensorineural hearing loss"),
    ("H91", "Другая потеря слуха", "Other hearing loss"),
    ("H92", "Оталгия и истечения из уха", "Otalgia and effusion of ear"),
    ("H93", "Другие болезни уха", "Other disorders of ear"),

    # ===== I00-I99 — Болезни системы кровообращения =====
    ("I00", "Ревматическая лихорадка без упоминания о вовлечении сердца", "Rheumatic fever without heart involvement"),
    ("I01", "Ревматическая лихорадка с вовлечением сердца", "Rheumatic fever with heart involvement"),
    ("I05", "Ревматические болезни митрального клапана", "Rheumatic mitral valve diseases"),
    ("I06", "Ревматические болезни аортального клапана", "Rheumatic aortic valve diseases"),
    ("I08", "Поражения нескольких клапанов", "Multiple valve diseases"),
    ("I10", "Эссенциальная (первичная) гипертензия", "Essential (primary) hypertension"),
    ("I11", "Гипертензивная болезнь сердца", "Hypertensive heart disease"),
    ("I12", "Гипертензивная болезнь почек", "Hypertensive renal disease"),
    ("I13", "Гипертензивная болезнь сердца и почек", "Hypertensive heart and renal disease"),
    ("I15", "Вторичная гипертензия", "Secondary hypertension"),
    ("I20", "Стенокардия", "Angina pectoris"),
    ("I21", "Острый инфаркт миокарда", "Acute myocardial infarction"),
    ("I22", "Повторный инфаркт миокарда", "Subsequent myocardial infarction"),
    ("I23", "Текущие осложнения острого инфаркта миокарда", "Complications following acute MI"),
    ("I24", "Другие формы острой ишемической болезни сердца", "Other acute ischaemic heart diseases"),
    ("I25", "Хроническая ишемическая болезнь сердца", "Chronic ischaemic heart disease"),
    ("I26", "Лёгочная эмболия", "Pulmonary embolism"),
    ("I27", "Другие лёгочно-сердечные болезни", "Other pulmonary heart diseases"),
    ("I30", "Острый перикардит", "Acute pericarditis"),
    ("I31", "Другие болезни перикарда", "Other diseases of pericardium"),
    ("I33", "Острый и подострый эндокардит", "Acute and subacute endocarditis"),
    ("I34", "Неревматические поражения митрального клапана", "Non-rheumatic mitral valve disorders"),
    ("I35", "Неревматические поражения аортального клапана", "Non-rheumatic aortic valve disorders"),
    ("I40", "Острый миокардит", "Acute myocarditis"),
    ("I42", "Кардиомиопатия", "Cardiomyopathy"),
    ("I44", "Предсердно-желудочковая блокада и блокада левой ножки", "AV block and left bundle-branch block"),
    ("I45", "Другие нарушения проводимости", "Other conduction disorders"),
    ("I46", "Остановка сердца", "Cardiac arrest"),
    ("I47", "Пароксизмальная тахикардия", "Paroxysmal tachycardia"),
    ("I48", "Фибрилляция и трепетание предсердий", "Atrial fibrillation and flutter"),
    ("I49", "Другие нарушения сердечного ритма", "Other cardiac arrhythmias"),
    ("I50", "Сердечная недостаточность", "Heart failure"),
    ("I51", "Осложнения и неточно описанные болезни сердца", "Complications and ill-defined heart diseases"),
    ("I60", "Субарахноидальное кровоизлияние", "Subarachnoid haemorrhage"),
    ("I61", "Внутримозговое кровоизлияние", "Intracerebral haemorrhage"),
    ("I62", "Другое нетравматическое внутричерепное кровоизлияние", "Other nontraumatic intracranial haemorrhage"),
    ("I63", "Инфаркт мозга", "Cerebral infarction"),
    ("I64", "Инсульт неуточнённый", "Stroke, not specified as haemorrhage or infarction"),
    ("I65", "Закупорка и стеноз прецеребральных артерий", "Occlusion / stenosis of precerebral arteries"),
    ("I67", "Другие цереброваскулярные болезни", "Other cerebrovascular diseases"),
    ("I69", "Последствия цереброваскулярных болезней", "Sequelae of cerebrovascular disease"),
    ("I70", "Атеросклероз", "Atherosclerosis"),
    ("I71", "Аневризма и расслоение аорты", "Aortic aneurysm and dissection"),
    ("I72", "Другие формы аневризмы", "Other aneurysm"),
    ("I73", "Другие болезни периферических сосудов", "Other peripheral vascular diseases"),
    ("I74", "Эмболия и тромбоз артерий", "Arterial embolism and thrombosis"),
    ("I80", "Флебит и тромбофлебит", "Phlebitis and thrombophlebitis"),
    ("I82", "Другие эмболии и тромбозы вен", "Other venous embolism and thrombosis"),
    ("I83", "Варикозное расширение вен нижних конечностей", "Varicose veins of lower extremities"),
    ("I84", "Геморрой", "Haemorrhoids"),
    ("I86", "Варикозное расширение вен других локализаций", "Varicose veins of other sites"),
    ("I87", "Другие поражения вен", "Other disorders of veins"),
    ("I88", "Неспецифический лимфаденит", "Nonspecific lymphadenitis"),
    ("I95", "Гипотензия", "Hypotension"),
    ("I99", "Другие неуточнённые болезни системы кровообращения", "Other / unspecified disorders of circulatory system"),

    # ===== J00-J99 — Болезни органов дыхания =====
    ("J00", "Острый назофарингит (насморк)", "Acute nasopharyngitis (common cold)"),
    ("J01", "Острый синусит", "Acute sinusitis"),
    ("J02", "Острый фарингит", "Acute pharyngitis"),
    ("J03", "Острый тонзиллит", "Acute tonsillitis"),
    ("J04", "Острый ларингит и трахеит", "Acute laryngitis and tracheitis"),
    ("J05", "Острый обструктивный ларингит и эпиглоттит", "Acute obstructive laryngitis and epiglottitis"),
    ("J06", "Острые инфекции верхних дыхательных путей", "Acute upper respiratory infections"),
    ("J09", "Грипп, вызванный идентифицированным вирусом зоонозного происхождения", "Influenza due to identified zoonotic virus"),
    ("J10", "Грипп, вызванный идентифицированным сезонным вирусом", "Influenza due to identified seasonal virus"),
    ("J11", "Грипп, вирус не идентифицирован", "Influenza, virus not identified"),
    ("J12", "Вирусная пневмония", "Viral pneumonia"),
    ("J13", "Пневмония, вызванная Streptococcus pneumoniae", "Pneumonia due to Streptococcus pneumoniae"),
    ("J14", "Пневмония, вызванная Haemophilus influenzae", "Pneumonia due to Haemophilus influenzae"),
    ("J15", "Бактериальная пневмония другая", "Other bacterial pneumonia"),
    ("J16", "Пневмония, вызванная другими инфекционными агентами", "Pneumonia due to other infectious organisms"),
    ("J17", "Пневмония при болезнях, классифицированных в других рубриках", "Pneumonia in diseases classified elsewhere"),
    ("J18", "Пневмония без уточнения возбудителя", "Pneumonia, unspecified organism"),
    ("J20", "Острый бронхит", "Acute bronchitis"),
    ("J21", "Острый бронхиолит", "Acute bronchiolitis"),
    ("J22", "Острая инфекция нижних дыхательных путей неуточнённая", "Unspecified acute lower respiratory infection"),
    ("J30", "Вазомоторный и аллергический ринит", "Vasomotor and allergic rhinitis"),
    ("J31", "Хронический ринит, назофарингит и фарингит", "Chronic rhinitis, nasopharyngitis and pharyngitis"),
    ("J32", "Хронический синусит", "Chronic sinusitis"),
    ("J33", "Полип носа", "Nasal polyp"),
    ("J34", "Другие болезни носа и носовых пазух", "Other disorders of nose and nasal sinuses"),
    ("J35", "Хронические болезни миндалин и аденоидов", "Chronic diseases of tonsils and adenoids"),
    ("J37", "Хронический ларингит и ларинготрахеит", "Chronic laryngitis and laryngotracheitis"),
    ("J38", "Болезни голосовых связок и гортани", "Diseases of vocal cords and larynx"),
    ("J40", "Бронхит неуточнённый", "Bronchitis, not specified as acute or chronic"),
    ("J41", "Простой и слизисто-гнойный хронический бронхит", "Simple and mucopurulent chronic bronchitis"),
    ("J42", "Хронический бронхит неуточнённый", "Unspecified chronic bronchitis"),
    ("J43", "Эмфизема", "Emphysema"),
    ("J44", "Хроническая обструктивная лёгочная болезнь (ХОБЛ)", "Chronic obstructive pulmonary disease (COPD)"),
    ("J45", "Астма", "Asthma"),
    ("J46", "Астматический статус", "Status asthmaticus"),
    ("J47", "Бронхоэктатическая болезнь", "Bronchiectasis"),
    ("J60", "Пневмокониоз шахтёра", "Coalworker pneumoconiosis"),
    ("J62", "Пневмокониоз, вызванный пылью с содержанием кремния", "Pneumoconiosis due to silica"),
    ("J67", "Гиперсенситивный пневмонит", "Hypersensitivity pneumonitis"),
    ("J80", "Респираторный дистресс-синдром взрослых (ОРДС)", "Adult respiratory distress syndrome (ARDS)"),
    ("J81", "Лёгочный отёк", "Pulmonary oedema"),
    ("J84", "Другие интерстициальные лёгочные болезни", "Other interstitial pulmonary diseases"),
    ("J85", "Абсцесс лёгкого и средостения", "Abscess of lung and mediastinum"),
    ("J86", "Эмпиема плевры", "Pyothorax"),
    ("J90", "Плевральный выпот", "Pleural effusion"),
    ("J93", "Пневмоторакс", "Pneumothorax"),
    ("J96", "Дыхательная недостаточность", "Respiratory failure"),
    ("J98", "Другие респираторные нарушения", "Other respiratory disorders"),

    # ===== K00-K93 — Болезни органов пищеварения =====
    ("K00", "Нарушения развития и прорезывания зубов", "Disorders of tooth development"),
    ("K02", "Кариес зубов", "Dental caries"),
    ("K03", "Другие болезни твёрдых тканей зубов", "Other diseases of hard tissues of teeth"),
    ("K04", "Болезни пульпы и периапикальных тканей", "Diseases of pulp and periapical tissues"),
    ("K05", "Гингивит и болезни пародонта", "Gingivitis and periodontal diseases"),
    ("K11", "Болезни слюнных желёз", "Diseases of salivary glands"),
    ("K12", "Стоматит и родственные поражения", "Stomatitis and related lesions"),
    ("K20", "Эзофагит", "Oesophagitis"),
    ("K21", "Гастроэзофагеальный рефлюкс (ГЭРБ)", "Gastro-oesophageal reflux disease (GERD)"),
    ("K22", "Другие болезни пищевода", "Other diseases of oesophagus"),
    ("K25", "Язва желудка", "Gastric ulcer"),
    ("K26", "Язва двенадцатиперстной кишки", "Duodenal ulcer"),
    ("K27", "Пептическая язва неуточнённая", "Peptic ulcer, site unspecified"),
    ("K28", "Гастроеюнальная язва", "Gastrojejunal ulcer"),
    ("K29", "Гастрит и дуоденит", "Gastritis and duodenitis"),
    ("K30", "Диспепсия", "Dyspepsia"),
    ("K31", "Другие болезни желудка и двенадцатиперстной кишки", "Other diseases of stomach and duodenum"),
    ("K35", "Острый аппендицит", "Acute appendicitis"),
    ("K37", "Аппендицит неуточнённый", "Unspecified appendicitis"),
    ("K40", "Паховая грыжа", "Inguinal hernia"),
    ("K41", "Бедренная грыжа", "Femoral hernia"),
    ("K42", "Пупочная грыжа", "Umbilical hernia"),
    ("K43", "Грыжа передней брюшной стенки", "Ventral hernia"),
    ("K44", "Диафрагмальная грыжа", "Diaphragmatic hernia"),
    ("K50", "Болезнь Крона", "Crohn disease"),
    ("K51", "Язвенный колит", "Ulcerative colitis"),
    ("K52", "Другие неинфекционные гастроэнтерит и колит", "Other non-infective gastroenteritis and colitis"),
    ("K57", "Дивертикулярная болезнь кишечника", "Diverticular disease of intestine"),
    ("K58", "Синдром раздражённого кишечника", "Irritable bowel syndrome"),
    ("K59", "Другие функциональные нарушения кишечника", "Other functional intestinal disorders"),
    ("K60", "Трещина и свищ области заднего прохода", "Anal fissure and fistula"),
    ("K63", "Другие болезни кишечника", "Other diseases of intestine"),
    ("K65", "Перитонит", "Peritonitis"),
    ("K70", "Алкогольная болезнь печени", "Alcoholic liver disease"),
    ("K71", "Токсическое поражение печени", "Toxic liver disease"),
    ("K72", "Печёночная недостаточность", "Hepatic failure"),
    ("K73", "Хронический гепатит", "Chronic hepatitis"),
    ("K74", "Фиброз и цирроз печени", "Fibrosis and cirrhosis of liver"),
    ("K76", "Другие болезни печени", "Other diseases of liver"),
    ("K80", "Желчнокаменная болезнь", "Cholelithiasis"),
    ("K81", "Холецистит", "Cholecystitis"),
    ("K85", "Острый панкреатит", "Acute pancreatitis"),
    ("K86", "Другие болезни поджелудочной железы", "Other diseases of pancreas"),
    ("K90", "Нарушения всасывания в кишечнике", "Intestinal malabsorption"),
    ("K92", "Другие болезни органов пищеварения", "Other diseases of digestive system"),

    # ===== L00-L99 — Болезни кожи =====
    ("L00", "Синдром стафилококкового поражения кожи", "Staphylococcal scalded skin syndrome"),
    ("L01", "Импетиго", "Impetigo"),
    ("L02", "Абсцесс кожи, фурункул и карбункул", "Cutaneous abscess, furuncle and carbuncle"),
    ("L03", "Флегмона", "Cellulitis"),
    ("L04", "Острый лимфаденит", "Acute lymphadenitis"),
    ("L08", "Другие местные инфекции кожи", "Other local skin infections"),
    ("L20", "Атопический дерматит", "Atopic dermatitis"),
    ("L21", "Себорейный дерматит", "Seborrhoeic dermatitis"),
    ("L22", "Пелёночный дерматит", "Diaper dermatitis"),
    ("L23", "Аллергический контактный дерматит", "Allergic contact dermatitis"),
    ("L25", "Контактный дерматит неуточнённый", "Unspecified contact dermatitis"),
    ("L27", "Дерматит вследствие приёма веществ внутрь", "Dermatitis due to substances taken internally"),
    ("L28", "Простой хронический лишай и почесуха", "Lichen simplex chronicus and prurigo"),
    ("L29", "Зуд", "Pruritus"),
    ("L30", "Другие дерматиты", "Other dermatitis"),
    ("L40", "Псориаз", "Psoriasis"),
    ("L43", "Красный плоский лишай", "Lichen planus"),
    ("L50", "Крапивница", "Urticaria"),
    ("L51", "Эритема многоформная", "Erythema multiforme"),
    ("L70", "Угри", "Acne"),
    ("L72", "Фолликулярная киста кожи", "Follicular cysts of skin"),
    ("L80", "Витилиго", "Vitiligo"),
    ("L82", "Себорейный кератоз", "Seborrhoeic keratosis"),
    ("L85", "Другие эпидермальные утолщения", "Other epidermal thickening"),
    ("L98", "Другие болезни кожи", "Other disorders of skin"),

    # ===== M00-M99 — Болезни костно-мышечной системы =====
    ("M00", "Гнойный артрит", "Pyogenic arthritis"),
    ("M02", "Реактивные артропатии", "Reactive arthropathies"),
    ("M05", "Серопозитивный ревматоидный артрит", "Seropositive rheumatoid arthritis"),
    ("M06", "Другие ревматоидные артриты", "Other rheumatoid arthritis"),
    ("M08", "Юношеский артрит", "Juvenile arthritis"),
    ("M10", "Подагра", "Gout"),
    ("M13", "Другие артриты", "Other arthritis"),
    ("M15", "Полиартроз", "Polyarthrosis"),
    ("M16", "Коксартроз", "Coxarthrosis"),
    ("M17", "Гонартроз", "Gonarthrosis"),
    ("M19", "Другие артрозы", "Other arthrosis"),
    ("M20", "Приобретённые деформации пальцев кистей и стоп", "Acquired deformities of fingers and toes"),
    ("M21", "Другие приобретённые деформации конечностей", "Other acquired deformities of limbs"),
    ("M23", "Внутрисуставные поражения колена", "Internal derangement of knee"),
    ("M25", "Другие поражения суставов", "Other joint disorders"),
    ("M30", "Узелковый полиартериит", "Polyarteritis nodosa"),
    ("M32", "Системная красная волчанка", "Systemic lupus erythematosus"),
    ("M33", "Дерматополимиозит", "Dermatopolymyositis"),
    ("M34", "Системный склероз", "Systemic sclerosis"),
    ("M35", "Другие системные поражения соединительной ткани", "Other systemic involvement of connective tissue"),
    ("M41", "Сколиоз", "Scoliosis"),
    ("M42", "Остеохондроз позвоночника", "Spinal osteochondrosis"),
    ("M45", "Анкилозирующий спондилит", "Ankylosing spondylitis"),
    ("M48", "Другие спондилопатии", "Other spondylopathies"),
    ("M50", "Поражения межпозвоночных дисков шейного отдела", "Cervical disc disorders"),
    ("M51", "Другие поражения межпозвоночных дисков", "Other intervertebral disc disorders"),
    ("M54", "Дорсалгия", "Dorsalgia (back pain)"),
    ("M60", "Миозит", "Myositis"),
    ("M65", "Синовит и теносиновит", "Synovitis and tenosynovitis"),
    ("M70", "Поражения мягких тканей при перегрузке", "Soft tissue disorders related to use / pressure"),
    ("M75", "Поражения плеча", "Shoulder lesions"),
    ("M77", "Энтезопатии", "Enthesopathies"),
    ("M79", "Другие болезни мягких тканей", "Other soft tissue disorders"),
    ("M80", "Остеопороз с патологическим переломом", "Osteoporosis with pathological fracture"),
    ("M81", "Остеопороз без патологического перелома", "Osteoporosis without pathological fracture"),
    ("M85", "Другие нарушения плотности костной ткани", "Other disorders of bone density"),
    ("M86", "Остеомиелит", "Osteomyelitis"),

    # ===== N00-N99 — Болезни мочеполовой системы =====
    ("N00", "Острый нефритический синдром", "Acute nephritic syndrome"),
    ("N01", "Быстро прогрессирующий нефритический синдром", "Rapidly progressive nephritic syndrome"),
    ("N03", "Хронический нефритический синдром", "Chronic nephritic syndrome"),
    ("N04", "Нефротический синдром", "Nephrotic syndrome"),
    ("N10", "Острый тубуло-интерстициальный нефрит (пиелонефрит)", "Acute tubulo-interstitial nephritis"),
    ("N11", "Хронический тубуло-интерстициальный нефрит", "Chronic tubulo-interstitial nephritis"),
    ("N13", "Обструктивная уропатия и рефлюкс-уропатия", "Obstructive and reflux uropathy"),
    ("N17", "Острая почечная недостаточность", "Acute renal failure"),
    ("N18", "Хроническая болезнь почек", "Chronic kidney disease"),
    ("N19", "Почечная недостаточность неуточнённая", "Unspecified kidney failure"),
    ("N20", "Камни почки и мочеточника", "Calculus of kidney and ureter"),
    ("N21", "Камни нижних отделов мочевыводящих путей", "Calculus of lower urinary tract"),
    ("N23", "Почечная колика неуточнённая", "Unspecified renal colic"),
    ("N28", "Другие болезни почки и мочеточника", "Other disorders of kidney and ureter"),
    ("N30", "Цистит", "Cystitis"),
    ("N31", "Нервно-мышечная дисфункция мочевого пузыря", "Neuromuscular dysfunction of bladder"),
    ("N34", "Уретрит и уретральный синдром", "Urethritis and urethral syndrome"),
    ("N39", "Другие болезни мочевыделительной системы", "Other disorders of urinary system"),
    ("N40", "Гиперплазия предстательной железы", "Hyperplasia of prostate"),
    ("N41", "Воспалительные болезни предстательной железы", "Inflammatory diseases of prostate"),
    ("N43", "Гидроцеле и сперматоцеле", "Hydrocele and spermatocele"),
    ("N45", "Орхит и эпидидимит", "Orchitis and epididymitis"),
    ("N48", "Другие болезни полового члена", "Other disorders of penis"),
    ("N60", "Доброкачественная дисплазия молочной железы", "Benign mammary dysplasia"),
    ("N61", "Воспалительные болезни молочной железы", "Inflammatory disorders of breast"),
    ("N63", "Образование в молочной железе неуточнённое", "Unspecified lump in breast"),
    ("N70", "Сальпингит и оофорит", "Salpingitis and oophoritis"),
    ("N71", "Воспалительные болезни матки", "Inflammatory disease of uterus"),
    ("N72", "Воспалительные болезни шейки матки", "Inflammatory disease of cervix uteri"),
    ("N73", "Другие воспалительные болезни женских тазовых органов", "Other female pelvic inflammatory diseases"),
    ("N76", "Другие воспалительные болезни влагалища и вульвы", "Other inflammation of vagina and vulva"),
    ("N80", "Эндометриоз", "Endometriosis"),
    ("N81", "Выпадение женских половых органов", "Female genital prolapse"),
    ("N83", "Невоспалительные поражения яичника, маточной трубы и связки", "Non-inflammatory disorders of ovary, fallopian tube"),
    ("N84", "Полип женских половых органов", "Polyp of female genital tract"),
    ("N85", "Другие невоспалительные болезни матки", "Other non-inflammatory disorders of uterus"),
    ("N87", "Дисплазия шейки матки", "Dysplasia of cervix uteri"),
    ("N91", "Отсутствие, скудные и редкие менструации", "Absent, scanty and rare menstruation"),
    ("N92", "Обильные, частые и нерегулярные менструации", "Excessive, frequent and irregular menstruation"),
    ("N94", "Болевые и другие состояния, связанные с менструальным циклом", "Pain and other conditions associated with menstrual cycle"),
    ("N95", "Менопаузные и другие околоменопаузные нарушения", "Menopausal and other perimenopausal disorders"),
    ("N97", "Женское бесплодие", "Female infertility"),

    # ===== O00-O99 — Беременность, роды, послеродовый период =====
    ("O00", "Внематочная беременность", "Ectopic pregnancy"),
    ("O02", "Другие неправильные продукты зачатия", "Other abnormal products of conception"),
    ("O03", "Самопроизвольный аборт", "Spontaneous abortion"),
    ("O04", "Медицинский аборт", "Medical abortion"),
    ("O10", "Существовавшая ранее гипертензия, осложняющая беременность", "Pre-existing hypertension complicating pregnancy"),
    ("O11", "Существовавшая ранее гипертензия с присоединившейся преэклампсией", "Pre-existing hypertensive disorder with superimposed pre-eclampsia"),
    ("O13", "Гестационная гипертензия без значительной протеинурии", "Gestational hypertension"),
    ("O14", "Преэклампсия", "Pre-eclampsia"),
    ("O15", "Эклампсия", "Eclampsia"),
    ("O20", "Кровотечение в ранние сроки беременности", "Haemorrhage in early pregnancy"),
    ("O21", "Чрезмерная рвота беременных", "Excessive vomiting in pregnancy"),
    ("O23", "Инфекции мочеполовых путей при беременности", "Infections of genitourinary tract in pregnancy"),
    ("O24", "Сахарный диабет при беременности", "Diabetes mellitus in pregnancy"),
    ("O26", "Ведение беременности при других состояниях", "Maternal care for other conditions"),
    ("O30", "Многоплодная беременность", "Multiple gestation"),
    ("O36", "Медицинская помощь матери при других установленных или предполагаемых состояниях плода", "Maternal care for other known/suspected fetal problems"),
    ("O40", "Многоводие", "Polyhydramnios"),
    ("O42", "Преждевременный разрыв плодных оболочек", "Premature rupture of membranes"),
    ("O44", "Предлежание плаценты", "Placenta praevia"),
    ("O45", "Преждевременная отслойка плаценты", "Premature separation of placenta"),
    ("O46", "Дородовое кровотечение", "Antepartum haemorrhage"),
    ("O60", "Преждевременные роды и роды до срока", "Preterm labour and delivery"),
    ("O63", "Затяжные роды", "Long labour"),
    ("O68", "Роды и родоразрешение, осложнившиеся стрессом плода", "Labour and delivery complicated by fetal stress"),
    ("O72", "Послеродовое кровотечение", "Postpartum haemorrhage"),
    ("O80", "Роды одноплодные, самопроизвольное родоразрешение", "Single spontaneous delivery"),
    ("O82", "Роды одноплодные, родоразрешение посредством кесарева сечения", "Single delivery by caesarean section"),
    ("O85", "Послеродовый сепсис", "Puerperal sepsis"),
    ("O86", "Другие послеродовые инфекции", "Other puerperal infections"),
    ("O88", "Акушерская эмболия", "Obstetric embolism"),
    ("O90", "Осложнения послеродового периода", "Complications of puerperium"),
    ("O99", "Другие болезни матери, осложняющие беременность, роды и послеродовый период", "Other maternal diseases complicating pregnancy"),

    # ===== P00-P96 — Перинатальные состояния =====
    ("P05", "Замедленный рост и недостаточность питания плода", "Slow fetal growth and fetal malnutrition"),
    ("P07", "Расстройства, связанные с малой массой тела при рождении и недоношенностью", "Disorders related to short gestation and low birth weight"),
    ("P08", "Расстройства, связанные с большой массой тела при рождении", "Disorders related to long gestation and high birth weight"),
    ("P22", "Дыхательное расстройство у новорождённого", "Respiratory distress of newborn"),
    ("P23", "Врождённая пневмония", "Congenital pneumonia"),
    ("P24", "Неонатальные аспирационные синдромы", "Neonatal aspiration syndromes"),
    ("P28", "Другие респираторные нарушения, возникшие в перинатальном периоде", "Other respiratory conditions of newborn"),
    ("P36", "Бактериальный сепсис новорождённого", "Bacterial sepsis of newborn"),
    ("P39", "Другие инфекции, специфичные для перинатального периода", "Other neonatal infections"),
    ("P55", "Гемолитическая болезнь плода и новорождённого", "Haemolytic disease of fetus and newborn"),
    ("P59", "Неонатальная желтуха", "Neonatal jaundice"),
    ("P70", "Преходящие нарушения углеводного обмена у новорождённого", "Transitory disorders of carbohydrate metabolism in newborn"),
    ("P77", "Некротизирующий энтероколит у плода и новорождённого", "Necrotising enterocolitis of newborn"),
    ("P91", "Другие нарушения церебрального статуса у новорождённого", "Other disturbances of cerebral status of newborn"),
    ("P95", "Внутриутробная гибель плода неуточнённой причины", "Fetal death of unspecified cause"),

    # ===== Q00-Q99 — Врождённые аномалии =====
    ("Q00", "Анэнцефалия и подобные пороки развития", "Anencephaly and similar malformations"),
    ("Q03", "Врождённая гидроцефалия", "Congenital hydrocephalus"),
    ("Q05", "Spina bifida", "Spina bifida"),
    ("Q20", "Врождённые аномалии сердечных камер и соединений", "Congenital malformations of cardiac chambers"),
    ("Q21", "Врождённые аномалии сердечной перегородки", "Congenital malformations of cardiac septa"),
    ("Q23", "Врождённые аномалии аортального и митрального клапанов", "Congenital malformations of aortic / mitral valves"),
    ("Q25", "Врождённые аномалии крупных артерий", "Congenital malformations of great arteries"),
    ("Q35", "Расщелина нёба", "Cleft palate"),
    ("Q36", "Расщелина губы", "Cleft lip"),
    ("Q39", "Врождённые аномалии пищевода", "Congenital malformations of oesophagus"),
    ("Q42", "Врождённое отсутствие кишки", "Congenital absence of intestine"),
    ("Q53", "Неопущение яичка", "Undescended testicle"),
    ("Q54", "Гипоспадия", "Hypospadias"),
    ("Q60", "Агенезия и другие редукционные пороки почки", "Renal agenesis and other reduction defects"),
    ("Q66", "Врождённые деформации стопы", "Congenital deformities of feet"),
    ("Q70", "Сращение пальцев", "Syndactyly"),
    ("Q79", "Врождённые аномалии костно-мышечной системы", "Congenital malformations of musculoskeletal system"),
    ("Q90", "Синдром Дауна", "Down syndrome"),
    ("Q96", "Синдром Тёрнера", "Turner syndrome"),
    ("Q99", "Другие хромосомные аномалии", "Other chromosomal abnormalities"),

    # ===== R00-R99 — Симптомы и отклонения =====
    ("R00", "Нарушения сердечного ритма", "Abnormalities of heart beat"),
    ("R01", "Сердечные шумы и другие звуки", "Cardiac murmurs and other cardiac sounds"),
    ("R03", "Аномальные показания артериального давления без диагноза", "Abnormal blood-pressure reading without diagnosis"),
    ("R04", "Кровотечение из дыхательных путей", "Haemorrhage from respiratory passages"),
    ("R05", "Кашель", "Cough"),
    ("R06", "Анормальное дыхание", "Abnormalities of breathing"),
    ("R07", "Боль в горле и в груди", "Pain in throat and chest"),
    ("R09", "Другие симптомы и признаки, относящиеся к системе кровообращения и дыхания", "Other respiratory / circulatory symptoms"),
    ("R10", "Боль в области живота и таза", "Abdominal and pelvic pain"),
    ("R11", "Тошнота и рвота", "Nausea and vomiting"),
    ("R13", "Дисфагия", "Dysphagia"),
    ("R14", "Метеоризм и родственные состояния", "Flatulence and related conditions"),
    ("R15", "Недержание кала", "Faecal incontinence"),
    ("R17", "Желтуха неуточнённая", "Unspecified jaundice"),
    ("R18", "Асцит", "Ascites"),
    ("R19", "Другие симптомы со стороны органов пищеварения", "Other symptoms involving digestive system"),
    ("R20", "Нарушения чувствительности кожи", "Disturbances of skin sensation"),
    ("R21", "Сыпь и другие неспецифические кожные высыпания", "Rash and other nonspecific skin eruption"),
    ("R22", "Локализованное припухание, образование на коже", "Localised swelling, mass and lump of skin"),
    ("R25", "Анормальные непроизвольные движения", "Abnormal involuntary movements"),
    ("R26", "Анормальная походка", "Abnormalities of gait and mobility"),
    ("R29", "Другие симптомы, относящиеся к нервной и костно-мышечной системам", "Other symptoms of nervous / musculoskeletal systems"),
    ("R30", "Боль при мочеиспускании", "Pain associated with micturition"),
    ("R31", "Неспецифическая гематурия", "Unspecified haematuria"),
    ("R32", "Недержание мочи неуточнённое", "Unspecified urinary incontinence"),
    ("R33", "Задержка мочи", "Retention of urine"),
    ("R34", "Анурия и олигурия", "Anuria and oliguria"),
    ("R35", "Полиурия", "Polyuria"),
    ("R40", "Сонливость, ступор и кома", "Somnolence, stupor and coma"),
    ("R41", "Другие симптомы и признаки, относящиеся к познавательной способности", "Other cognitive symptoms"),
    ("R42", "Головокружение", "Dizziness and giddiness"),
    ("R44", "Другие симптомы, относящиеся к ощущениям", "Other symptoms involving sensations"),
    ("R45", "Симптомы, относящиеся к эмоциональному состоянию", "Symptoms involving emotional state"),
    ("R47", "Нарушения речи", "Speech disturbances"),
    ("R50", "Лихорадка неуточнённого происхождения", "Fever of unknown origin"),
    ("R51", "Головная боль", "Headache"),
    ("R52", "Боль не классифицированная в других рубриках", "Pain, not elsewhere classified"),
    ("R53", "Недомогание и утомляемость", "Malaise and fatigue"),
    ("R55", "Обморок и коллапс", "Syncope and collapse"),
    ("R56", "Судороги, не классифицированные в других рубриках", "Convulsions, not elsewhere classified"),
    ("R57", "Шок не классифицированный в других рубриках", "Shock, not elsewhere classified"),
    ("R60", "Отёк не классифицированный в других рубриках", "Oedema, not elsewhere classified"),
    ("R63", "Симптомы и признаки, связанные с приёмом пищи", "Symptoms and signs concerning food and fluid intake"),
    ("R73", "Повышенное содержание глюкозы в крови", "Elevated blood glucose level"),
    ("R74", "Анормальные показатели сывороточных ферментов", "Abnormal serum enzyme levels"),
    ("R79", "Другие анормальные показатели биохимических исследований", "Other abnormal findings of blood chemistry"),
    ("R80", "Изолированная протеинурия", "Isolated proteinuria"),
    ("R94", "Анормальные результаты функциональных диагностических исследований", "Abnormal results of function studies"),
    ("R99", "Другие неточно обозначенные и неуточнённые причины смерти", "Other ill-defined and unspecified causes of mortality"),

    # ===== S00-T98 — Травмы и отравления =====
    ("S00", "Поверхностная травма головы", "Superficial injury of head"),
    ("S01", "Открытая рана головы", "Open wound of head"),
    ("S02", "Перелом черепа и лицевых костей", "Fracture of skull and facial bones"),
    ("S06", "Внутричерепная травма", "Intracranial injury"),
    ("S09", "Другие и неуточнённые травмы головы", "Other and unspecified injuries of head"),
    ("S10", "Поверхностная травма шеи", "Superficial injury of neck"),
    ("S20", "Поверхностная травма грудной клетки", "Superficial injury of thorax"),
    ("S22", "Перелом рёбер, грудины и грудного отдела позвоночника", "Fracture of rib(s), sternum and thoracic spine"),
    ("S27", "Травма других и неуточнённых органов грудной полости", "Injury of other and unspecified intrathoracic organs"),
    ("S30", "Поверхностная травма живота, нижней части спины и таза", "Superficial injury of abdomen, lower back, pelvis"),
    ("S32", "Перелом пояснично-крестцового отдела позвоночника и таза", "Fracture of lumbar spine and pelvis"),
    ("S36", "Травма органов брюшной полости", "Injury of intra-abdominal organs"),
    ("S40", "Поверхностная травма плечевого пояса и плеча", "Superficial injury of shoulder and upper arm"),
    ("S42", "Перелом ключицы, лопатки и плечевой кости", "Fracture of clavicle, scapula, humerus"),
    ("S52", "Перелом костей предплечья", "Fracture of forearm"),
    ("S62", "Перелом на уровне запястья и кисти", "Fracture at wrist and hand level"),
    ("S70", "Поверхностная травма бедра", "Superficial injury of hip and thigh"),
    ("S72", "Перелом бедренной кости", "Fracture of femur"),
    ("S82", "Перелом голени", "Fracture of lower leg"),
    ("S83", "Вывих, растяжение и перенапряжение капсульно-связочного аппарата коленного сустава", "Dislocation/sprain of joints/ligaments of knee"),
    ("S92", "Перелом стопы", "Fracture of foot"),
    ("T00", "Поверхностные травмы нескольких областей тела", "Superficial injuries involving multiple body regions"),
    ("T07", "Множественные травмы неуточнённые", "Unspecified multiple injuries"),
    ("T14", "Травма неуточнённой области тела", "Injury of unspecified body region"),
    ("T20", "Термические и химические ожоги головы и шеи", "Burns and corrosions of head and neck"),
    ("T22", "Термический ожог плеча и верхней конечности", "Burn of shoulder and upper limb"),
    ("T24", "Термический ожог нижней конечности", "Burn of lower limb"),
    ("T30", "Термический и химический ожог неуточнённой локализации", "Burn / corrosion of body region unspecified"),
    ("T31", "Термические ожоги, классифицированные в зависимости от площади", "Burns classified according to surface involvement"),
    ("T39", "Отравление неопиоидными анальгетиками", "Poisoning by non-opioid analgesics"),
    ("T40", "Отравление наркотиками и психодислептиками", "Poisoning by narcotics and psychodysleptics"),
    ("T42", "Отравление противоэпилептическими и снотворными средствами", "Poisoning by antiepileptic / hypnotic drugs"),
    ("T50", "Отравление прочими медикаментами", "Poisoning by other drugs"),
    ("T51", "Токсическое действие алкоголя", "Toxic effect of alcohol"),
    ("T63", "Токсическое действие, обусловленное контактом с ядовитыми животными", "Toxic effect of contact with venomous animals"),
    ("T78", "Анафилактический шок и другие неблагоприятные эффекты", "Anaphylactic shock and other adverse effects"),
    ("T81", "Осложнения процедур не классифицированные в других рубриках", "Complications of procedures NEC"),
    ("T88", "Другие осложнения хирургического и терапевтического вмешательства", "Other complications of surgical and medical care"),
    ("T98", "Последствия других уточнённых внешних причин", "Sequelae of other specified external causes"),

    # ===== Z00-Z99 — Факторы здоровья =====
    ("Z00", "Общий осмотр и обследование лиц, не имеющих жалоб", "General examination of persons without complaint"),
    ("Z01", "Другие специальные обследования лиц без жалоб", "Other special examinations of persons without complaint"),
    ("Z02", "Обследование и контакты с медицинскими службами в административных целях", "Examination and encounter for administrative purposes"),
    ("Z03", "Медицинское наблюдение и оценка при подозрении на заболевание", "Medical observation for suspected diseases"),
    ("Z11", "Скрининговое обследование с целью выявления инфекционных и паразитарных болезней", "Screening for infectious and parasitic diseases"),
    ("Z12", "Скрининговое обследование с целью выявления новообразований", "Screening for malignant neoplasms"),
    ("Z13", "Скрининговое обследование с целью выявления других болезней", "Screening for other diseases"),
    ("Z21", "Бессимптомный статус инфицирования вирусом ВИЧ", "Asymptomatic HIV infection status"),
    ("Z22", "Носитель инфекционных болезней", "Carrier of infectious disease"),
    ("Z23", "Необходимость иммунизации против отдельной инфекционной болезни", "Need for vaccination against single bacterial disease"),
    ("Z30", "Наблюдение по поводу контрацепции", "Encounter for contraceptive management"),
    ("Z32", "Обследование и тесты для установления беременности", "Encounter for pregnancy test and confirmation"),
    ("Z33", "Состояние беременности", "Pregnant state"),
    ("Z34", "Наблюдение за течением нормальной беременности", "Encounter for supervision of normal pregnancy"),
    ("Z37", "Исход родов", "Outcome of delivery"),
    ("Z38", "Живорождённые в зависимости от места рождения", "Liveborn infants according to place of birth"),
    ("Z39", "Послеродовое наблюдение и обследование", "Encounter for maternal postpartum care"),
    ("Z51", "Другие виды медицинской помощи", "Other medical care"),
    ("Z71", "Лица, обращающиеся в учреждения здравоохранения для консультации", "Persons encountering health services for counselling"),
    ("Z72", "Проблемы, связанные с образом жизни", "Problems related to lifestyle"),
    ("Z76", "Лица, контактирующие со службой здравоохранения по другим обстоятельствам", "Persons encountering health services in other circumstances"),
    ("Z80", "Семейный анамнез злокачественного новообразования", "Family history of malignant neoplasm"),
    ("Z82", "Семейный анамнез некоторых инвалидностей и хронических болезней", "Family history of certain disabilities and chronic diseases"),
    ("Z85", "Личный анамнез злокачественного новообразования", "Personal history of malignant neoplasm"),
    ("Z86", "Личный анамнез некоторых других болезней", "Personal history of certain other diseases"),
    ("Z87", "Личный анамнез других болезней и состояний", "Personal history of other diseases and conditions"),
    ("Z90", "Приобретённое отсутствие органов", "Acquired absence of organs"),
    ("Z95", "Наличие сердечных и сосудистых имплантатов и трансплантатов", "Presence of cardiac and vascular implants"),
    ("Z96", "Наличие других функциональных имплантатов", "Presence of other functional implants"),
    ("Z99", "Зависимость от вспомогательных механизмов и устройств", "Dependence on enabling machines and devices"),
]
